AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:

  # DynamoDB Table
  BudgetTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: BudgetTable
      AttributeDefinitions:
        - AttributeName: "ExpenseId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "ExpenseId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  # Lambda Function for Adding Expenses
  AddExpenseFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: add_expense.handler
      Runtime: python3.13
      CodeUri: src/add_expense/  # Ensure this directory exists and contains your code
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref BudgetTable

  # Additional Lambda Functions for editing, deleting expenses, income, etc.
  # (Repeat the same pattern for other Lambda functions)
  
Outputs:
  AddExpenseFunctionArn:
    Description: "Add Expense Function ARN"
    Value: !GetAtt AddExpenseFunction.Arn

  BudgetTableName:
    Description: "The name of the DynamoDB Table"
    Value: !Ref BudgetTable
